default_platform(:ios)

platform :ios do
  desc "Build BondTrack and upload a new build to TestFlight"
  lane :beta do
    setup_ci if ENV["CI"]

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false
    )

    increment_build_number(
      xcodeproj: "BondTrack.xcodeproj",
      build_number: ENV["GITHUB_RUN_NUMBER"] || Time.now.to_i.to_s
    )

    build_app(
      project: "BondTrack.xcodeproj",
      scheme: "BondTrack",
      export_method: "app-store",
      output_directory: "build",
      output_name: "BondTrack.ipa",
      xcargs: "DEVELOPMENT_TEAM=#{ENV['TEAM_ID']} CODE_SIGN_STYLE=Manual " \
              "PROVISIONING_PROFILE_SPECIFIER='#{ENV['PROFILE_NAME']}' " \
              "CODE_SIGN_IDENTITY='Apple Distribution'"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      distribute_external: false
    )
  end
end
